server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_trolley_rush?createDatabaseIfNotExist=true
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: create
